### ISSUE TITLE
CVPR error

### ISSUE THREAD

**Issue by sorrowyn** [guicho271828/aaai-template#4]
![图片](https://user-images.githubusercontent.com/19569162/158733472-a62cb137-b9e0-4973-bee9-7cb77a3440bc.png)

**Comment by guicho271828** [comment]
I usually do not submit to cvpr so unfortunately I can provide no support for your debugging. Errors in latex tends to be very paper specific and library specific, the way you use your custom command, and so forth. But if you can improve the cvpr specific part, I am more than grateful. Thank you

**Comment by sorrowyn** [comment]
thank you!
I have solved this problem.
\citet   -> \cite
